### ISSUE TITLE
UX: Scroll top button should have pointer cursor

### ISSUE THREAD

**Issue by thangngoc89** [Kipalog/Issue-tracker#17]
It's pretty weird when hover a button without pointer cursor

``` css
.scroll-top {
  cursor: pointer
}
```
